[theme]
primaryColor="#4a90e2"          # Azul suave
backgroundColor="#f5f5f5"       # Cinza bem claro
secondaryBackgroundColor="#e0e0e0" # Cinza médio
textColor="#333333"             # Texto quase preto
font="sans serif"
